2024-07-03 19:30:30 DEBUG SECRET_KEY: Can you guess it?
2024-07-03 19:30:32 INFO The form has been created
2024-07-03 19:30:38 INFO The form has been created
2024-07-03 19:30:38 INFO The form has been submitted and validated
2024-07-03 19:30:38 ERROR Exception on /auth/login [POST]
Traceback (most recent call last):
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
MySQLdb.ProgrammingError: (1146, "Table 'Flasheeta$default.users' doesn't exist")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/home/Flasheeta/Flasheeta/app/web_routes/auth_routes.py", line 53, in login
    user = User.query.filter_by(name=username).first()
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2728, in first
    return self.limit(1)._iter().first()  # type: ignore
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2351, in execute
    return self._execute_internal(
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/orm/session.py", line 2236, in _execute_internal
    result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
    result = conn.execute(
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2353, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/home/Flasheeta/.virtualenvs/myenv/lib/python3.8/site-packages/MySQLdb/connections.py", line 261, in query
    _mysql.connection.query(self, query)
sqlalchemy.exc.ProgrammingError: (MySQLdb.ProgrammingError) (1146, "Table 'Flasheeta$default.users' doesn't exist")
[SQL: SELECT users.name AS users_name, users.id AS users_id, users.created_at AS users_created_at, users.updated_at AS users_updated_at 
FROM users 
WHERE users.name = %s 
 LIMIT %s]
[parameters: ('Messi', 1)]
(Background on this error at: https://sqlalche.me/e/20/f405)
2024-07-03 19:35:55 DEBUG SECRET_KEY: Can you guess it?
2024-07-03 19:35:58 ERROR Error: Directory migrations already exists and is not empty
2024-07-03 19:36:28 DEBUG SECRET_KEY: Can you guess it?
2024-07-03 19:37:11 DEBUG SECRET_KEY: Can you guess it?
2024-07-03 19:37:44 DEBUG SECRET_KEY: Can you guess it?
2024-07-03 19:37:47 INFO The form has been created
2024-07-03 19:37:51 INFO The form has been created
2024-07-03 19:37:51 INFO The form has been submitted and validated
2024-07-03 19:37:52 INFO Invalid Username
2024-07-03 19:43:19 DEBUG SECRET_KEY: Can you guess it?
2024-07-03 19:43:22 INFO The form has been created
2024-07-03 19:43:36 INFO The form has been created
2024-07-03 19:43:36 INFO The form has been submitted and validated
2024-07-03 19:43:36 INFO The user has logged in
2024-07-03 19:44:30 INFO The form has been created
2024-07-03 19:45:25 INFO The form has been created
2024-07-03 19:46:03 INFO The form has been created
2024-07-03 19:46:03 INFO The form has been submitted and validated
2024-07-03 19:46:03 INFO The user has logged in
2024-07-03 19:46:26 INFO Updated flashcard data: question=New card, answer=9999999999, deck_id=004310f6-2c1c-41a6-9356-4a813d37886c
2024-07-03 19:46:43 INFO The form has been created
2024-07-03 19:48:02 INFO The form has been created
2024-07-03 19:48:43 INFO The form has been created
2024-07-03 19:48:55 INFO The form has been created
2024-07-03 19:48:55 INFO The form has been submitted and validated
2024-07-03 19:48:55 INFO The user has logged in
2024-07-03 19:49:53 INFO The form has been created
2024-07-03 19:57:50 DEBUG SECRET_KEY: Can you guess it?
2024-07-03 19:57:58 INFO The form has been created
2024-07-03 19:57:58 INFO The form has been submitted and validated
2024-07-03 19:57:58 INFO The user has logged in
2024-07-03 19:58:07 INFO The form has been created
2024-07-03 19:59:42 INFO The form has been created
2024-07-03 19:59:45 INFO The form has been created
2024-07-03 19:59:45 INFO The form has been submitted and validated
2024-07-03 19:59:45 INFO The user has logged in
2024-07-03 20:17:13 DEBUG SECRET_KEY: b0798256a02bbaa09366483a57f960fd721abb491f851aae
2024-07-03 20:17:16 INFO The form has been created
2024-07-03 20:17:20 INFO The form has been created
2024-07-03 20:17:25 INFO The form has been created
2024-07-03 20:17:25 INFO The form has been submitted and validated
2024-07-03 20:17:26 INFO The user has logged in
2024-07-03 20:34:24 DEBUG SECRET_KEY: be6a89345592d5173a1c9d923a0c9436ed9632bdc34b3a0f
2024-07-03 20:35:11 DEBUG SECRET_KEY: 5d7196a8c7e77d7a4f5e36291e0ffbdfe1aeef85f26cb676
2024-07-03 20:39:17 DEBUG SECRET_KEY: eb9403d9c300ca2d7e48ca37dd8750a63907283a72e6777b24a59488fcb587f4
2024-07-03 20:41:09 INFO The form has been created
2024-07-03 20:41:13 INFO The form has been created
2024-07-03 20:41:13 INFO The form has been submitted and validated
2024-07-03 20:41:13 INFO The user has logged in
2024-07-03 20:41:44 INFO The form has been created
2024-07-03 20:43:45 INFO The form has been created
